version: "3.9"

volumes:
  maven-repo:


services:

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped


  api-gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8080:8080"

    volumes:
      - ./application.yml:/app/application.yml

      - maven-repo:/root/.m2

    depends_on:
      - redis

    restart: unless-stopped


  downstream-service:
    build: ./DownStream-Service
    container_name: downstream_service
    ports:
      - "8081:8080"

    volumes:
      - maven-repo:/root/.m2

    restart: unless-stopped
